apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gameservers.carrier.ocgi.dev
spec:
  names:
    kind: GameServer
    plural: gameservers
    shortNames:
      - gs
    singular: gameserver
  group: carrier.ocgi.dev
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .status.state
          name: State
          type: string
        - jsonPath: .status.address
          name: Address
          type: string
        - jsonPath: .status.loadBalancerStatus.ingress[*].ports[*].externalPort
          name: Port
          type: string
        - jsonPath: .status.loadBalancerStatus.ingress[*].ports[*].externalPortRange
          name: PortRange
          type: string
        - jsonPath: .status.nodeName
          name: Node
          type: string
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
          required:
            - spec
          properties:
            spec:
              x-kubernetes-preserve-unknown-fields: true
              type: object
              required:
                - template
              properties:
                template:
                  type: object
                  required:
                    - spec
                  properties:
                    spec:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                      required:
                        - containers
                      properties:
                        containers:
                          type: array
                          minItems: 1
                          items:
                            x-kubernetes-preserve-unknown-fields: true
                            type: object
                            required:
                              - image
                            properties:
                              name:
                                type: string
                                minLength: 0
                                maxLength: 63
                                pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
                              image:
                                type: string
                                minLength: 1
                ports:
                  type: array
                  minItems: 0
                  items:
                    type: object
                    properties:
                      portPolicy:
                        type: string
                        enum:
                          - Dynamic
                          - Static
                          - LoadBalancer
                      protocol:
                        type: string
                        enum:
                          - UDP
                          - TCP
                          - TCPUDP
                      containerPort:
                        type: integer
                        minimum: 1
                        maximum: 65535
                      containerPortRange:
                        type: object
                        properties:
                          minPort:
                            type: integer
                            minimum: 1
                            maximum: 65535
                          maxPort:
                            type: integer
                            minimum: 1
                            maximum: 65535
                      hostPort:
                        type: integer
                        minimum: 1
                        maximum: 65535
                scheduling:
                  type: string
                  enum:
                    - Default
                    - MostAllocated
                    - LeastAllocated
      subresources:
        # status enables the status subresource.
        status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gameserversets.carrier.ocgi.dev
spec:
  group: carrier.ocgi.dev
  scope: Namespaced
  names:
    kind: GameServerSet
    plural: gameserversets
    shortNames:
      - gss
      - gsset
    singular: gameserverset
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.scheduling
          name: Scheduling
          type: string
        - jsonPath: .spec.replicas
          name: Desired
          type: integer
        - jsonPath: .status.replicas
          name: Current
          type: integer
        - jsonPath: .status.readyReplicas
          name: Ready
          type: integer
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
          properties:
            spec:
              x-kubernetes-preserve-unknown-fields: true
              type: object
              required:
                - replicas
                - template
              properties:
                replicas:
                  type: integer
                  minimum: 0
                scheduling:
                  type: string
                  enum:
                    - MostAllocated
                    - LeastAllocated
                    - Default
                template:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
                  required:
                    - spec
                  properties:
                    spec:
                      x-kubernetes-preserve-unknown-fields: true
                      type: object
                      required:
                        - template
                      properties:
                        template:
                          x-kubernetes-preserve-unknown-fields: true
                          type: object
                          required:
                            - spec
                          properties:
                            spec:
                              x-kubernetes-preserve-unknown-fields: true
                              type: object
                              required:
                                - containers
                              properties:
                                containers:
                                  x-kubernetes-preserve-unknown-fields: true
                                  type: array
                                  minItems: 1
                                  items:
                                    type: object
                                    required:
                                      - image
                                    properties:
                                      name:
                                        type: string
                                        minLength: 0
                                        maxLength: 63
                                        pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
                                      image:
                                        type: string
                                        minLength: 1
                        ports:
                          type: array
                          minItems: 0
                          items:
                            type: object
                            properties:
                              portPolicy:
                                type: string
                                enum:
                                  - Dynamic
                                  - Static
                                  - LoadBalancer
                              protocol:
                                type: string
                                enum:
                                  - UDP
                                  - TCP
                                  - TCPUDP
                              containerPort:
                                type: integer
                                minimum: 1
                                maximum: 65535
                              containerPortRange:
                                type: object
                                properties:
                                  minPort:
                                    type: integer
                                    minimum: 1
                                    maximum: 65535
                                  maxPort:
                                    type: integer
                                    minimum: 1
                                    maximum: 65535
                              hostPort:
                                type: integer
                                minimum: 1
                                maximum: 65535
                        scheduling:
                          type: string
                          enum:
                            - Default
                            - MostAllocated
                            - LeastAllocated
      subresources:
        # status enables the status subresource.
        status: {}
        # scale enables the scale subresource.
        scale:
          # specReplicasPath defines the JSONPath inside of a custom resource that corresponds to Scale.Spec.Replicas.
          specReplicasPath: .spec.replicas
          # statusReplicasPath defines the JSONPath inside of a custom resource that corresponds to Scale.Status.Replicas.
          statusReplicasPath: .status.replicas
          # labelSelectorPath defines the JSONPath inside of a custom resource that corresponds to Scale.Status.Selector.
          labelSelectorPath: .status.selector
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: squads.carrier.ocgi.dev
spec:
  group: carrier.ocgi.dev
  scope: Namespaced
  names:
    kind: Squad
    plural: squads
    shortNames:
      - sqd
    singular: squad
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.scheduling
          name: Scheduling
          type: string
        - jsonPath: .spec.replicas
          name: Desired
          type: integer
        - jsonPath: .status.replicas
          name: Current
          type: integer
        - jsonPath: .status.updatedReplicas
          name: UP-TO-DATE
          type: integer
        - jsonPath: .status.readyReplicas
          name: Ready
          type: integer
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
          properties:
            spec:
              x-kubernetes-preserve-unknown-fields: true
              type: object
              required:
                - template
              properties:
                replicas:
                  type: integer
                  minimum: 0
                scheduling:
                  type: string
                  enum:
                    - MostAllocated
                    - LeastAllocated
                strategy:
                  type: object
                  properties:
                    type:
                      type: string
                      enum:
                        - Recreate
                        - RollingUpdate
                        - CanaryUpdate
                        - InplaceUpdate
                template:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
                  required:
                    - spec
                  properties:
                    spec:
                      x-kubernetes-preserve-unknown-fields: true
                      type: object
                      required:
                        - template
                      properties:
                        template:
                          x-kubernetes-preserve-unknown-fields: true
                          type: object
                          required:
                            - spec
                          properties:
                            spec:
                              x-kubernetes-preserve-unknown-fields: true
                              type: object
                              required:
                                - containers
                              properties:
                                containers:
                                  type: array
                                  minItems: 1
                                  items:
                                    x-kubernetes-preserve-unknown-fields: true
                                    type: object
                                    required:
                                      - image
                                    properties:
                                      name:
                                        type: string
                                        minLength: 0
                                        maxLength: 63
                                        pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
                                      image:
                                        type: string
                                        minLength: 1
                        ports:
                          type: array
                          minItems: 0
                          items:
                            type: object
                            properties:
                              portPolicy:
                                type: string
                                enum:
                                  - Dynamic
                                  - Static
                                  - LoadBalancer
                              protocol:
                                type: string
                                enum:
                                  - UDP
                                  - TCP
                                  - TCPUDP
                              containerPort:
                                type: integer
                                minimum: 1
                                maximum: 65535
                              containerPortRange:
                                type: object
                                properties:
                                  minPort:
                                    type: integer
                                    minimum: 1
                                    maximum: 65535
                                  maxPort:
                                    type: integer
                                    minimum: 1
                                    maximum: 65535
                              hostPort:
                                type: integer
                                minimum: 1
                                maximum: 65535
                        scheduling:
                          type: string
                          enum:
                            - Default
                            - MostAllocated
                            - LeastAllocated
                revisionHistoryLimit:
                  type: integer
                  minimum: 0
                paused:
                  type: boolean
      subresources:
        # status enables the status subresource.
        status: {}
        # scale enables the scale subresource.
        scale:
          # specReplicasPath defines the JSONPath inside of a custom resource that corresponds to Scale.Spec.Replicas.
          specReplicasPath: .spec.replicas
          # statusReplicasPath defines the JSONPath inside of a custom resource that corresponds to Scale.Status.Replicas.
          statusReplicasPath: .status.replicas
          # labelSelectorPath defines the JSONPath inside of a custom resource that corresponds to Scale.Status.Selector.
          labelSelectorPath: .status.selector
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webhookconfigurations.carrier.ocgi.dev
spec:
  scope: Namespaced
  names:
    kind: WebhookConfiguration
    plural: webhookconfigurations
    shortNames:
      - wc
    singular: webhookconfiguration
  group: carrier.ocgi.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          x-kubernetes-preserve-unknown-fields: true
          type: object
          required:
            - webhooks
          properties:
            webhooks:
              x-kubernetes-preserve-unknown-fields: true
              type: array
              minItems: 1
              items:
                x-kubernetes-preserve-unknown-fields: true
                type: object
                required:
                  - type
                  - name
                  - clientConfig
                minItems: 1
                properties:
                  name:
                    type: string
                    minLength: 1
                    maxLength: 128
                  type:
                    type: string
                    enum:
                      - ReadinessWebhook
                      - DeletableWebhook
                      - ConstraintWebhook
                  requestPolicy:
                    type: string
                    enum:
                      - Once
                      - Always
                  clientConfig:
                    type: object
                    properties:
                      url:
                        type: string
                      service:
                        type: object
                        required:
                          - namespace
                          - name
                          - path
                          - port
                        properties:
                          namespace:
                            type: string
                            minLength: 1
                            maxLength: 128
                            pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
                          name:
                            type: string
                            minLength: 1
                            maxLength: 128
                            pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
                          path:
                            type: string
                          port:
                            type: integer
                            minimum: 0
