apiVersion: v1
kind: ServiceAccount
metadata:
  name: carrier
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: carrier
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
      - events
      - leases
      - endpoints
    verbs:
      - "*"
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - watch
      - get
      - list
  - apiGroups:
      - carrier.ocgi.dev
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carrier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: carrier
subjects:
  - kind: ServiceAccount
    name: carrier
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrier
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carrier-service
  template:
    metadata:
      labels:
        app: carrier-service
    spec:
      serviceAccountName: carrier
      containers:
        - args:
            - --election-resource-lock=endpoints
            - --v=5
          image: ocgi/carrier-controller:latest
          imagePullPolicy: IfNotPresent
          name: carrier-controller
